vim.opt.background = 'dark'
vim.opt.number = true
vim.opt.expandtab = true -- use spaces
vim.opt.shiftwidth = 2
vim.opt.tabstop = 2
vim.opt.wrap = false
vim.opt.colorcolumn = '+1'
vim.opt.hidden = true
vim.g.leader = "space"
